Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,6 +24,10 @@ jobs:
       uses: gradle/actions/setup-gradle@v4
       with:
         gradle-version: '8.2'
+    - name: Prepare Logo
+      run: |
+        mkdir -p app/src/main/res/drawable
+        cp logo.png app/src/main/res/drawable/logo.png || echo "Logo not found"
     - name: Build with Gradle
       run: gradle assembleDebug
     - name: Rename APK
